--SQL Basic Case Study

use Retail_database

--Data preparation and understanding


--1. What is the total number of rows in each of the 3 tables in the database? 
--Q1--BEGIN

Select 'Customer' [Records], count(*)[No Of Records]
from Customer
	union all
Select 'Product_Category'[Records], count(*)[No Of Records]
from prod_cat_info
	union
Select 'Transactions' [Records], count(*)[No Of Records]
from Transactions

--Q1--END


--2. What is the total number of transactions that have a return?
--Q2--BEGIN

select count (Qty) 
from Transactions
where Qty < 0

--Q2--END


--3. Convert the date variables into valid date formats 
--Q3--BEGIN 

/* I have already coverted dates to correct
fromat before importing data into sql*/

--Q3--END


--4. What is the time range of the transaction data available for analysis? 
--Q4--BEGIN

select DATEDIFF(day,min(tran_date), max(tran_date)) AS days,
 DATEDIFF(month,min(tran_date), max(tran_date)) AS MONTHS,
 DATEDIFF(YEAR,min(tran_date), max(tran_date)) AS YEARS
 from Transactions

--Q4--END

--5. Which product category does the sub-category “DIY” belong to? 
--Q5--BEGIN

select * from prod_cat_info
where prod_subcat ='DIY'

--Q5--END






--Data Analysis



--1. Which channel is most frequently used for transactions? 
--Q1--BEGIN 

Select top 1 (Store_type)[channel],count (store_type)[Count_of_transaction]
from Transactions
group by Store_type
order by count (store_type) desc

--Q1--END


--2. What is the count of Male and Female customers in the database? 
--Q2--BEGIN

select  gender,COUNT(GENDER)[COUNT]
from Customer
group by Gender
having Gender = 'M' OR Gender = 'F'

--OR including blanks

select  gender,COUNT(GENDER)[COUNT]
from Customer
group by Gender

--Q2--END


--3. From which city do we have the maximum number of customers and how many? 
--Q3--BEGIN      
	
Select top 1 C.city_code, count(customer_id)[Count_of_Customer]
	from Customer C 
	GROUP BY C.city_code
	ORDER BY count(customer_id) desc

--Q3--END


--4. How many sub-categories are there under the Books category? 
--Q4--BEGIN

Select prod_cat,count (prod_sub_cat_code)[Count_of_sub_cat]
from prod_cat_info
group by prod_cat
Having prod_cat='Books'


--Q4--END


--5. What is the maximum quantity of products ever ordered? 
--Q5--BEGIN

select prod_cat, max(Qty)[Max_qty_ordered]
from Transactions T 
	inner join prod_cat_info P on T.prod_cat_code=P.prod_cat_code 
	AND T.prod_subcat_code = P.prod_sub_cat_code
	group by prod_cat


--Q5--END


--6. What is the net total revenue generated in categories Electronics and Books? 
--Q6--BEGIN

select sum(total_amt)[Net_total_revenue]
from Transactions T 
	inner join prod_cat_info P on T.prod_cat_code=P.prod_cat_code
	AND T.prod_subcat_code = P.prod_sub_cat_code
where prod_cat ='Electronics' or prod_cat ='Books'

--Q6--END


--7. How many customers have >10 transactions with us, excluding returns? 	
--Q7--BEGIN  

Select cust_id ,count(transaction_id)[Transaction_count] 
from Transactions
where Qty > 0
group by cust_id
having count(transaction_id) > 10 	

--Q7--END	


--8. What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”? 
--Q8--BEGIN

select sum(total_amt)[Net_total_revenue]
from Transactions T 
	inner join prod_cat_info P on T.prod_cat_code=P.prod_cat_code
	AND T.prod_subcat_code = P.prod_sub_cat_code
where Store_type ='Flagship store' and prod_cat ='Electronics' or prod_cat ='Books' 

--Q8--END


--9. What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat.
--Q9--BEGIN

select prod_subcat, sum(total_amt)[Net_total_revenue]
from Transactions T 
	inner join prod_cat_info P on T.prod_cat_code=P.prod_cat_code
	AND T.prod_subcat_code = P.prod_sub_cat_code
		INNER JOIN Customer C ON T.cust_id=C.customer_Id
where  prod_cat ='Electronics'  AND Gender ='M'
group by prod_subcat

--Q9--END


--10.What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales? 
--Q10--BEGIN
	
SELECT TOP 5 
  SUM(CASE WHEN total_amt >0 THEN total_amt ELSE 0 END) AS total_sales,
  SUM(CASE WHEN total_amt <0 THEN total_amt ELSE 0 END) AS total_returns,
  100 * SUM(CASE WHEN total_amt >0 THEN total_amt ELSE 0 END) / SUM(total_amt) AS sales_percentage,
  100 * SUM(CASE WHEN total_amt <0 THEN total_amt ELSE 0 END) / SUM(total_amt) AS retuns_percentage,
  P.prod_subcat
FROM Transactions T 
	inner join prod_cat_info P on T.prod_cat_code=P.prod_cat_code
	AND T.prod_subcat_code=P.prod_sub_cat_code
group by P.prod_subcat


 
--Q10--END


/*Q11. For all customers aged between 25 to 35 years find what is the net total revenue
generated by these consumers in last 30 days of transactions from max transaction
date available in the data? */

--Q11--Beginn	

select sum(total_amt) as total_sales
from Customer as T1 inner join Transactions as T2
			on T1.customer_Id =T2.cust_id
				where DOB between DATEADD(year,-35,(select max(tran_date)  from Transactions)) and
					DATEADD(year,-25,(select max(tran_date)  from Transactions)) and
					tran_date >=DATEADD(year,-30,(select max(tran_date)  from Transactions))

--Q11--END


--12.Which product category has seen the max value of returns in the last 3 months of transactions?
--Q12--BEGIN

SELECT TOP 1
P.prod_cat, COUNT(total_amt)RETURN_COUNT
FROM Transactions T 
	inner join prod_cat_info P on T.prod_cat_code=P.prod_cat_code
	AND T.prod_subcat_code=P.prod_sub_cat_code
	WHERE total_amt< 0 AND
	Tran_date >= DATEADD(MONTH,-3,(SELECT max(tran_date)FROM Transactions))
	GROUP BY prod_cat 
	ORDER BY COUNT(total_amt) DESC

	
--Q12--END


--13.Which store-type sells the maximum products; by value of sales amount and by quantity sold?
--Q13--BEGIN

SELECT TOP 1 
Store_type,SUM(total_amt)sales, SUM(Qty)quantity
FROM Transactions T inner join prod_cat_info P on T.prod_cat_code=P.prod_cat_code
AND T.prod_subcat_code=P.prod_sub_cat_code AND T.Qty > 0 and T.total_amt > 0
GROUP BY Store_type
order by SUM(total_amt) desc


--Q13--END


--14.What are the categories for which average revenue is above the overall average.
--Q14--BEGIN

select p.prod_cat,avg(total_amt) as Average
from (select t.*, avg(t.total_amt) over () as overall_average
		from Transactions T)t join
		prod_cat_info P 
		ON T.prod_cat_code=P.prod_cat_code
AND T.prod_subcat_code=P.prod_sub_cat_code
GROUP BY P.prod_cat,overall_average
HAVING AVG(t.total_amt)> overall_average
order by Average desc

--Q14--END


--15. Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.
--Q15--BEGIN

SELECT prod_cat, prod_subcat, avg(total_amt) as Avg_revenue, sum(total_amt) as total_revenue  
FROM Transactions T inner join prod_cat_info P on T.prod_cat_code=P.prod_cat_code
AND T.prod_subcat_code=P.prod_sub_cat_code 
where prod_cat in 
	(select top 5 prod_cat 
	 FROM Transactions T inner join prod_cat_info P on T.prod_cat_code=P.prod_cat_code
	 group by prod_cat
	 order by sum(qty) desc)
group by prod_cat, prod_subcat

--Q15--END




